2022-04-17 22:07:47,096 INFO    MainThread:25076 [wandb_setup.py:_flush():75] Loading settings from C:\Users\12500\.config\wandb\settings
2022-04-17 22:07:47,096 INFO    MainThread:25076 [wandb_setup.py:_flush():75] Loading settings from C:\Projects\Pytorch\Pytorch-UNet-master - 副本\wandb\settings
2022-04-17 22:07:47,098 INFO    MainThread:25076 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-17 22:07:47,098 INFO    MainThread:25076 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train - 副本.py', 'program': 'C:/Projects/Pytorch/Pytorch-UNet-master - 副本/train - 副本.py'}
2022-04-17 22:07:47,098 INFO    MainThread:25076 [wandb_setup.py:_flush():75] Applying login settings: {'anonymous': 'must'}
2022-04-17 22:07:47,099 INFO    MainThread:25076 [wandb_init.py:_log_setup():405] Logging user logs to C:\Projects\Pytorch\Pytorch-UNet-master - 副本\wandb\run-20220417_220747-10bkj8ee\logs\debug.log
2022-04-17 22:07:47,099 INFO    MainThread:25076 [wandb_init.py:_log_setup():406] Logging internal logs to C:\Projects\Pytorch\Pytorch-UNet-master - 副本\wandb\run-20220417_220747-10bkj8ee\logs\debug-internal.log
2022-04-17 22:07:47,099 INFO    MainThread:25076 [wandb_init.py:init():439] calling init triggers
2022-04-17 22:07:47,099 INFO    MainThread:25076 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-04-17 22:07:47,099 INFO    MainThread:25076 [wandb_init.py:init():492] starting backend
2022-04-17 22:07:47,099 INFO    MainThread:25076 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2022-04-17 22:07:47,104 INFO    MainThread:25076 [backend.py:ensure_launched():219] starting backend process...
2022-04-17 22:07:47,191 INFO    MainThread:25076 [backend.py:ensure_launched():225] started backend process with pid: 26160
2022-04-17 22:07:47,191 INFO    MainThread:25076 [wandb_init.py:init():501] backend started and connected
2022-04-17 22:07:47,193 INFO    MainThread:25076 [wandb_init.py:init():565] updated telemetry
2022-04-17 22:07:47,194 INFO    MainThread:25076 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-17 22:08:17,204 INFO    MainThread:25076 [interface_shared.py:_communicate_run():322] couldn't get run from backend
2022-04-17 22:08:17,204 ERROR   MainThread:25076 [wandb_init.py:init():601] backend process timed out
2022-04-17 22:08:17,204 ERROR   MainThread:25076 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
